#!/bin/zsh

apt_install () {
    package_name=$1
    echo "Insatlling: "$package_name" ... "
    sudo apt -y install $package_name &>> $output_file   
    if apt list --installed python-dev &>> $output_file | grep -hq installed ; then 
        echo $package_name" installed" >> $log_file
    else
        echo $package_name" not installed" >> $log_file
    fi
}

github_install () {
    source=$1
    destination=$2
    echo "Insatlling: "$source" ... "
    if [[ -s $destination  ]]; then
        echo "$1 installed before" >> $log_file
    else
        git clone https://github.com/$source $destination &>> $output_file 
        echo "$1 installed" >> $log_file
    fi
}

snap_install () {
    package_name=$1
    echo "Insatlling: "$package_name " ... "
    sudo snap install $package_name &>> $output_file 
    if type -p $package_name > /dev/null; then
        echo $package_name "Installed" >> $log_file
    else
        echo $package_name "Not Installed" >> $log_file
    fi
}

composer_install () {
    echo "Insatlling: composer ... "
    if type -p composer > /dev/null; then
        echo "Composer Installed" >> $log_file
    else
        if type -p php > /dev/null; then
            curl -sS https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer
            chmod +x /usr/local/bin/composer
            echo "Composer Installed" >> $log_file
        fi
    fi
}

laravel_install () {
    echo "Installing: laravel ... "
    if type -p laravel > /dev/null; then
        echo "Laravel Installed ..." >> $log_file
    else
        if type -p composer > /dev/null; then
            composer global require "laravel/installer" &>> $output_file
            echo "Laravel/Installer Installed" >> $log_file
        fi
    fi
}

summary_title () {
    title=$1
    echo "#============" >> $log_file
    echo "# "$title >> $log_file
    echo "#============" >> $log_file
}

help () {
    echo "
    #==============================================================
    #      Command: 
    #              ./install [options] 
    #      Options: 
    #           -b,--basic  
    #               Basic Installation:
    #               Vim, Tmux, Zsh, basic packages.
    #           -f,--full 
    #               Full Installation:
    #               php-dev tools: composer, laravel, mycli
    #               packages: keepassx, mailspring, cmus, rofi ...
    #           -h,--help 
    #               Show help message     
    #==============================================================
   "
}

summary_head () {
    echo "#============" >> $log_file
    echo "# Summary    " >> $log_file
    echo "#============" >> $log_file
}

summary () {
    cat $log_file

    rm $log_file
    rm $output_file
    echo ' ______________'
    echo ' Enjoy '$USER
    echo ' --------------'
    echo '        \   ^__^'
    echo '         \  (oo)\_______'
    echo '            (__)\       )\/\'
    echo '                ||----w |'
    echo '                ||     ||'
    echo '                ||     ||'
    echo '                ||     ||'
    echo '                         '
}
