- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config", "~/.config/nvim"]

- create:
    - ~/Repos
    - ~/Work
    - ~/.config/coc/extensions

- link:
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.bashrc: bashrc
    ~/.tmux.conf: tmux.conf
    ~/.config/kitty: config/kitty
    ~/.config/rofi/config: rofi
    ~/.config/zsh: config/zsh
    ~/.fonts: fonts
    ~/.config/nvim/init.vim: init.vim
    ~/.config/nvim/plugins.vim: config/nvim/plugins.vim
    ~/.config/coc/coc-settings.json: config/nvim/coc-settings.json
    ~/.config/nvim/ginit.vim: config/nvim/ginit.vim
    ~/.config/nvim/lua/user/plugins.lua: config/lua/plugins.lua
    # TODO: NVIM LUA CONFIG
    # ~/.config/nvim/init.lua: init.lua
    # ~/.config/nvim/lua/user/options.lua: config/lua/options.lua
    # ~/.config/nvim/lua/user/mappings.lua: config/lua/mappings.lua
    # ~/.config/nvim/lua/user/vimplug.lua: config/lua/vimplug.lua
    # ~/.config/nvim/lua/user/lsp.lua: config/lua/lsp.lua

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - command: bash install-packages.sh 
      description: Installing and setting git, tmux, zsh, vim, nvim and nvim with all dependencies and plugins
      # stderr: true
    # - 
    #   command: chsh -s $(which zsh)
    #   description: Making zsh default shell
    #   stdin: true
    #   stdout: true
    #   stderr: true
    #   quiet: true
