- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- create:
    - ~/Repos
    - ~/Work

- link:
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.bashrc: bashrc
    ~/.tmux.conf: tmux.conf
    ~/.gitconfig: gitconfig
    ~/.config/nvim/init.vim: init.vim
    ~/.config/nvim: config/nvim
    ~/.config/kitty: config/kitty
    ~/.config/rofi/config: rofi
    ~/.config/zsh: config/zsh
    ~/.fonts: fonts

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [~/.tmux/plugins/tpm/bin/install_plugins; true, Installing tmux plugins]
    - [nvim +PlugUpdate +PlugClean! +qa, Installing vim plugins]
    - [cd ~/.config/coc/extensions/ && yarn --emoji true, Installing coc-nvim extension]
    - [sudo apt install -y git tmux zsh, Installing git, tmux, zsh]
    - 
      command: chsh -s $(which zsh)
      description: Making zsh the default shell
      stdin: true
      stdout: true
      stderr: true
      quiet: true
