- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config", "~/.config/nvim"]

- create:
    - ~/Repos
    - ~/Work

- link:
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.bashrc: bashrc
    ~/.tmux.conf: tmux.conf
    ~/.config/kitty: config/kitty
    ~/.config/rofi/config: rofi
    ~/.config/zsh: config/zsh
    ~/.fonts: fonts
    ~/.config/nvim/init.vim: init.vim
    ~/.config/nvim/plugins.vim: config/nvim/plugins.vim
    ~/.config/nvim/coc-settings.json: config/nvim/coc-settings.json
    ~/.config/nvim/ginit.vim: config/nvim/ginit.vim
    ~/.config/nvim/lua/user/plugins.lua: config/lua/plugins.lua
    # nvim lua
    # ~/.config/nvim/init.lua: init.lua
    # ~/.config/nvim/lua/user/options.lua: config/lua/options.lua
    # ~/.config/nvim/lua/user/mappings.lua: config/lua/mappings.lua
    # ~/.config/nvim/lua/user/vimplug.lua: config/lua/vimplug.lua
    # ~/.config/nvim/lua/user/lsp.lua: config/lua/lsp.lua

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [~/.tmux/plugins/tpm/bin/install_plugins; true, Installing tmux plugins]
    - [nvim +PlugUpdate +PlugClean! +qa, Installing vim plugins]
    - [cd ~/.config/coc/extensions/ && yarn --emoji true, Installing coc-nvim extension]
    - [sudo apt install -y git tmux zsh, Installing git, tmux, zsh]
    # - 
    #   command: chsh -s $(which zsh)
    #   description: Making zsh the default shell
    #   stdin: true
    #   stdout: true
    #   stderr: true
    #   quiet: true
