- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config", "~/.config/nvim"]

- create:
    - ~/Repos
    - ~/Work
    - ~/.config/rofi
    - ~/.config/nvim
    - ~/.local/scripts

- link:
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.bashrc: bashrc
    ~/.tmux.conf: tmux.conf
    ~/.config/kitty: config/kitty
    ~/.config/rofi/config: rofi
    ~/.config/zsh/exports.sh: config/zsh/exports.sh
    ~/.config/zsh/aliases.sh: config/zsh/aliases.sh
    ~/.config/zsh/functions.sh: config/zsh/functions.sh
    ~/.config/zsh/wincent_prompt.sh: config/zsh/wincent_prompt.sh
    ~/.config/zsh/bash_prompt.sh: config/zsh/bash_prompt.sh
    ~/.fonts: fonts
    ~/.config/nvim/init.lua: init.lua
    ~/.local/scripts/tmux-sessionizer: tmux-sessionizer

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - command: bash install-packages.sh 
      description: Installing and setting git, tmux, zsh, vim, nvim and nvim with all dependencies and plugins
      # stderr: true
    # - 
    #   command: chsh -s $(which zsh)
    #   description: Making zsh default shell
    #   stdin: true
    #   stdout: true
    #   stderr: true
    #   quiet: true
