- defaults:
    link:
      create: true
      relink: true
      force: true
    shell:
      stdin: true
      stdout: true
      stderr: true
      quiet: true

- clean: ["~", "~/.config", "~/.config/nvim"]

- create:
    - ~/Repos
    - ~/Work
    - ~/.config/coc/extensions 
    - ~/.config/polybar
    - ~/.config/i3
    - ~/.config/zsh
    - ~/.local/share/fonts

- link:
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.bashrc: bashrc
    ~/.xinitrc: xinitrc
    ~/.tmux.conf: tmux.conf
    ~/.config/:
      glob: true
      path: config/*
      exclude: [config/i3blocks, config/vscode]
    ~/.config/zsh: 
      path: config/zsh/*
      exclude: [plugins, wincent_prompt]

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - command: bash setup.sh 
      description: Setup i3, tmux, nvim, zsh, fonts 
    - command: chsh -s $(which zsh)
      description: Making zsh default shell
    - command: bash setup-git.sh
      description: Config git
