--- 
- name: "Update apt package cache"
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600  
  become: yes

- name: "Debug - Run shell commands"
  ansible.builtin.shell: |
    whoami
    pwd
  register: command_output

- name: "Debug - Display command output"
  ansible.builtin.debug:
    var: command_output.stdout
