username: john

package_list:
  - name: git
  - name: curl
  - name: tmux 
  - name: zsh 
  - name: htop
  - name: vim
  - name: nginx
  - name: rsync
  - name: just
  - name: fzf
  - name: kitty
  - name: ripgrep
  - name: stow
  - name: i3
  - name: rofi
  - name: polybar
  - name: xsel
  - name: zsh-syntax-highlighting
    apt: zsh-syntax-highlighting
  - name: lxappearance
    apt: lxappearance
    apk_ignore: yes
    yum_ignore: yes
    dnf_ignore: yes
    brew_ignore: yes
    zypper_ignore: yes
    pacman_ignore: yes
    portage_ignore: yes
    opkg_ignore: yes
  - name: nitrogen
    apt: nitrogen
    apk_ignore: yes
    yum_ignore: yes
    dnf_ignore: yes
    brew_ignore: yes
    zypper_ignore: yes
    pacman_ignore: yes
    portage_ignore: yes
    opkg_ignore: yes
  - name: picom
    apt: picom
    apk_ignore: yes
    yum_ignore: yes
    dnf_ignore: yes
    brew_ignore: yes
    zypper_ignore: yes
    pacman_ignore: yes
    portage_ignore: yes
    opkg_ignore: yes

docker_users:  
  - "{{ ansible_user }}"
