- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: 0700

- name: Debug ansible_user_dir
  debug:
    var: ansible_user_dir

- name: Copy private keys (strip _private suffix)
  copy:
    src: "{{ item }}"
    dest: "{{ role_path }}/{{ item | basename | regex_replace('_private$', '') }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0600
  with_fileglob:
    - "files/*_private"

- name: Copy public keys (rename _public to .pub)
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.ssh/{{ item | basename | regex_replace('_public$', '.pub') }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
  with_fileglob:
    - "files/*_public"

- name: Copy ssh config file
  copy:
    src: files/config
    dest: "{{ ansible_user_dir }}/.ssh/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
