- name: "SSH | Ensure .ssh directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: '0700'

- name: Debug ansible_user_dir
  ansible.builtin.debug:
    var: ansible_user_dir

- name: "Copy private keys"
  ansible.builtin.template:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ ansible_user_dir }}/.ssh/{{ item.dest }}"
    mode: '0600'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  loop:
    - { src: "private",   dest: "id_ed25519" }
    - { src: "hubeurope_private",   dest: "hubeurope" }
    - { src: "digex_private",   dest: "digex" }
    - { src: "agency_private",   dest: "agency" }
  loop_control:
    label: "{{ item.dest }}"

- name: "Copy public keys"
  ansible.builtin.template:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ ansible_user_dir }}/.ssh/{{ item.dest }}"
    mode: '0644'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  loop:
    - { src: "public",   dest: "id_ed25519.pub" }
    - { src: "hubeurope_public",   dest: "hubeurope.pub" }
    - { src: "digex_public",   dest: "digex.pub" }
  loop_control:
    label: "{{ item.dest }}"
