- name: "SSH | Ensure .ssh directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: '0700'

- name: Debug ansible_user_dir
  ansible.builtin.debug:
    var: ansible_user_dir

- name: "SSH | Copy private key"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/private"
    dest: "{{ ansible_user_dir }}/.ssh/id_ed25519"
    mode: '0600'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: "SSH | Copy public key"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/public"
    dest: "{{ ansible_user_dir }}/.ssh/id_ed25519.pub"
    mode: '0644'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: "SSH | Copy hubeurope private key"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/hubeurope_private"
    dest: "{{ ansible_user_dir }}/.ssh/hubeurope"
    mode: '0600'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: "SSH | Copy hubeurope public key"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/hubeurope_public"
    dest: "{{ ansible_user_dir }}/.ssh/hubeurope.pub"
    mode: '0644'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: "SSH | Copy dusseldorf private key"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dusseldorf_private"
    dest: "{{ ansible_user_dir }}/.ssh/dusseldorf"
    mode: '0600'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: "SSH | Copy dusseldorf public key"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dusseldorf_public"
    dest: "{{ ansible_user_dir }}/.ssh/dusseldorf.pub"
    mode: '0644'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
