---
- name: "Install zsh-autosuggestions"
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.zsh/zsh-autosuggestions
    depth: 1
    update: no

- name: "Copy content of secret file (encrypted with Ansible Vault) to ~/.secrets"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/secrets"
    dest: ~/.secrets
    mode: "0600"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: "Ensure default shell is zsh"
  become: yes
  when: lookup('env', 'USER') != "root"
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/bin/zsh
