#!/bin/zsh

source 'helper_functions'

summary_title Main-packages

apt_packages=(vim tmux curl openssh-server)
for i in $apt_packages; do
    apt_install $i
done

sources=(chriskempson/base16-shell.git zsh-users/zsh-autosuggestions tmux-plugins/tpm)
destinations=(~/.config/base16-shell ~/.zsh/zsh-autosuggestions ~/.tmux/plugins/tpm)

for (( i = 1; i <= ${#sources} ; i++ )); do
    github_install $sources[$i] $destinations[$i]
done
