#!/bin/zsh

echo '#============' >> $log_file
echo '# Symlinks ' >> $log_file
echo '#============' >> $log_file

files_to_remove=(bashrc bash)
for i in $files_to_remove ; do
    if [[ -a ~/.$i ]]; then
        sudo rm -rf ~/.$i > /dev/null 2>&1
        echo "Remove: ".$i >> $log_file
    fi
done

dirs_to_create=(vim zsh tmux)
for i in $dirs_to_create ; do
    if [[ ! -a ~/.$i ]]; then
        mkdir -p ~/.$i 
        echo "Create Dirctory: ".$i >> $log_file
    fi

done

files_to_symlink=(vimrc zshrc tmux.conf zsh/functions.sh zsh/aliases.sh dir_colors fonts vim/UltiSnips)
for i in $files_to_symlink; do
    if [[ -a ~/.$i ]]; then
        if [[ ! -L ~/.$i ]]; then
            sudo rm -rf ~/.$i > /dev/null 2>&1
            ln -sf $DOTFILES/$i ~/.$i
            echo "Create Symlink: "$i >> $log_file
        else
            echo "$i is a Symlink." >> $log_file
        fi
    else
        ln -sf $DOTFILES/$i ~/.$i
        echo "Create Symlink: "$i >> $log_file
    fi
done
