#!/bin/zsh

source 'helper_functions'

summary_title Vim-plugins

github_install VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

apt_packages=(build-essential cmake python-dev python3-dev exuberant-ctags)
for i in $apt_packages; do
    apt_install $i
done

# vim +PluginInstall +qall
