#!/bin/zsh

source 'helper_functions'

summary_title Web-dev-tools

sudo apt -y update &>> $output_file
sudo apt -y upgrade &>> $output_file
apt_packages=(php php-mbstring php-curl php-mcrypt php-gettext php-xml php-json php-zip mycli)

for i in $apt_packages ; do
    apt_install $i
done

composer_install
laravel_install
