---
- name: "I3 | {{ ansible_distribution }} | Install i3"
  ansible.builtin.apt:
    update_cache: yes
    name: i3
    state: present
  become: yes

- name: "I3 | {{ ansible_distribution }} | Install rofi"
  ansible.builtin.apt:
    update_cache: yes
    name: rofi
    state: present
  become: yes
