---
- name: "Config name, email, editor"
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: "user.name", value: "{{ git_user }}" }
    - { name: "user.email", value: "{{ git_email }}" }
    - { name: "core.editor", value: "nvim" }

- name: "Aliases and settings"
  git_config:
    name: "alias.{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { key: "oneline", value: "!git --paginate log --pretty=format:'%C(auto)%h%Creset %s%C(auto)%d%Creset %C(magenta bold)(%cr)%Creset %C(cyan)%Creset'" }
    - { key: "o", value: "oneline" }
    - { key: "wc", value: "diff ORIG_HEAD.." }
    - { key: "count", value: "!git --no-pager log --oneline | wc -l" }
    - { key: "committers", value: '!git log --format="%h %ce %s"' }

