# Enable rounded corners
# corner-radius = 10

# Optional: shadow behind windows
shadow = false
# shadow-radius = 8
# shadow-offset-x = -8
# shadow-offset-y = -8
# shadow-opacity = 0.25

inactive-opacity = 0.85
active-opacity = 1.0

# Enable fading (nice effect)
fading = false
fade-in-step = 0.03
fade-out-step = 0.03

# Avoid shadows on dock/panels
shadow-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'i3-frame'"
]
