---
- name: "Nvim | {{ ansible_distribution }} | Install prerequisites (APT)"
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop: "{{ nvim_apts }}"
  become: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: "Nvim | {{ ansible_distribution }} | Install prerequisites (Pacman)"
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ nvim_pacman }}"
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'

- name: "Nvim | {{ ansible_distribution }} | create directories"
  file:
    path: "{{ item }}"
    state: directory
    recurse: false
    mode: "0755"
  loop: "{{ nvim_dirs }}"

- name: "Nvim | {{ ansible_distribution }} | Clone source repo for build"
  git:
    repo: "{{ nvim_repo }}"
    dest: "{{ nvim_build_path }}"
    version: stable
    accept_hostkey: true
    depth: 1
    update: true
    force: true

- name: "Nvim | {{ ansible_distribution }} | clean up artifacts from prior builds"
  community.general.make:
    chdir: "{{ nvim_build_path }}"
    target: distclean

- name: "Nvim | {{ ansible_distribution }} | build release target"
  community.general.make:
    chdir: "{{ nvim_build_path }}"
    params:
      CMAKE_BUILD_TYPE: Release
      CMAKE_INSTALL_PREFIX: "{{ nvim_install_path }}"

- name: "Nvim | {{ ansible_distribution }} | install release target"
  become: yes
  community.general.make:
    chdir: "{{ nvim_build_path }}"
    params:
      CMAKE_BUILD_TYPE: Release
      CMAKE_INSTALL_PREFIX: "{{ nvim_install_path }}"
    target: install
  register: install_results

- name: "Nvim | {{ ansible_distribution }} | cleanup build folder"
  file:
    state: absent
    path: "{{ nvim_build_path }}"
  when:
    - nvim_remove_build
    - not install_results.failed
